### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Ccconvict72** [stuin/Sonic-Devices-API#1]
Everytime I try to load this mod, my game crashes. https://pastebin.com/3A2p0Xt3

**Comment by stuin** [comment]
I am aware of this but I will not be able to work on it much until after 12/12

**Comment by Ccconvict72** [comment]
> I am aware of this but I will not be able to work on it much until after 12/12

Alright, didnt know if I was missing something

**Comment by stuin** [comment]
Sorry about the long wait, a fixed version for 1.18.1 is now on curseforge and modrinth
